import type { CommentsFile } from "./types";

function formatDate(iso: string): string {
  const d = new Date(iso);
  return (
    d.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    }) +
    " " +
    d.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
    })
  );
}

export function buildCompanionMarkdown(
  fileName: string,
  commentsFile: CommentsFile,
  mdPath?: string
): string {
  const lines: string[] = [];

  lines.push(`# Comments — ${fileName}`);
  lines.push("");
  lines.push(
    "*Generated by Comment Threads. Do not edit — regenerated on save.*"
  );
  lines.push("");
  lines.push("---");

  // Sort thread IDs numerically
  const threadIds = Object.keys(commentsFile.comments).sort((a, b) => {
    const numA = parseInt(a.replace("c", ""), 10);
    const numB = parseInt(b.replace("c", ""), 10);
    return numA - numB;
  });

  let resolvedCount = 0;
  let openCount = 0;

  for (const id of threadIds) {
    const thread = commentsFile.comments[id];
    if (!thread) continue;

    const anchorText = thread.anchorText || "(no anchor)";
    let displayText = anchorText.replace(/[\r\n]+/g, " ").replace(/\s+/g, " ").trim();
    // Escape characters that break markdown link syntax
    displayText = displayText.replace(/[\[\]()]/g, "\\$&");
    if (displayText.length > 80) displayText = displayText.slice(0, 80) + "...";

    lines.push("");
    if (mdPath) {
      const uri = `obsidian://comment-threads?file=${encodeURIComponent(mdPath)}&comment=${id}`;
      lines.push(`> **[${id}]** on "[${displayText}](${uri})"`);
    } else {
      lines.push(`> **[${id}]** on "${displayText}"`);
    }
    lines.push("");

    for (const msg of thread.thread) {
      lines.push(`**${msg.author}** — ${formatDate(msg.timestamp)}`);
      lines.push(msg.body);
      lines.push("");
    }

    if (thread.resolved) {
      resolvedCount++;
      lines.push(
        `✅ *Resolved by ${thread.resolvedBy} — ${thread.resolvedAt ? formatDate(thread.resolvedAt) : ""}*`
      );
    } else {
      openCount++;
      lines.push("🟡 *Open*");
    }

    lines.push("");
    lines.push("---");
  }

  const total = resolvedCount + openCount;
  lines.push("");
  lines.push(
    `*${total} comment${total !== 1 ? "s" : ""} (${resolvedCount} resolved, ${openCount} open)*`
  );
  lines.push("");

  return lines.join("\n");
}
