import type { CommentsFile } from "./types";

const MARKER_RE = /<mark>([\s\S]*?)<\/mark><sup>\[c(\d+)\]<\/sup>/g;

function formatDate(iso: string): string {
  const d = new Date(iso);
  return (
    d.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    }) +
    " " +
    d.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
    })
  );
}

export function buildCompanionMarkdown(
  fileName: string,
  markdownContent: string,
  commentsFile: CommentsFile
): string {
  const lines: string[] = [];

  lines.push(`# Comments — ${fileName}`);
  lines.push("");
  lines.push(
    "*Generated by Comment Threads. Do not edit — regenerated on save.*"
  );
  lines.push("");
  lines.push("---");

  // Extract anchors in document order
  const anchors: { id: string; text: string }[] = [];
  let match;
  const re = new RegExp(MARKER_RE.source, "g");
  while ((match = re.exec(markdownContent)) !== null) {
    let text = match[1]!;
    if (text.length > 80) text = text.slice(0, 80) + "...";
    anchors.push({ id: `c${match[2]}`, text });
  }

  // Include unanchored threads (marker deleted but thread remains)
  const anchoredIds = new Set(anchors.map((a) => a.id));
  const allIds = Object.keys(commentsFile.comments);
  const unanchored = allIds.filter((id) => !anchoredIds.has(id));

  const orderedEntries = [
    ...anchors.map((a) => ({ id: a.id, text: a.text })),
    ...unanchored.map((id) => ({ id, text: "(unanchored)" })),
  ];

  let resolvedCount = 0;
  let openCount = 0;

  for (const entry of orderedEntries) {
    const thread = commentsFile.comments[entry.id];
    if (!thread) continue;

    lines.push("");
    lines.push(`> **[${entry.id}]** on "${entry.text}"`);
    lines.push("");

    for (const msg of thread.thread) {
      lines.push(`**${msg.author}** — ${formatDate(msg.timestamp)}`);
      lines.push(msg.body);
      lines.push("");
    }

    if (thread.resolved) {
      resolvedCount++;
      lines.push(
        `✅ *Resolved by ${thread.resolvedBy} — ${thread.resolvedAt ? formatDate(thread.resolvedAt) : ""}*`
      );
    } else {
      openCount++;
      lines.push("🟡 *Open*");
    }

    lines.push("");
    lines.push("---");
  }

  const total = resolvedCount + openCount;
  lines.push("");
  lines.push(
    `*${total} comment${total !== 1 ? "s" : ""} (${resolvedCount} resolved, ${openCount} open)*`
  );
  lines.push("");

  return lines.join("\n");
}
